mv xaa 110523_ASCOposter.html
mv xab conference_poster_benjamin_amoah.html
mv xac Chipeta_FHM_poster.html
mv xad INFER2011.html
mv xae ECFposter26May.html
mv xaf ISEE2009.html
mv xag peritoneal_dialysis.html
mv xah Ramis_poster_Zurich.html
mv xai deprivation.html
mv xaj leptospirosis.html
mv xak 101013_FINALPhaseI.html
mv xal variability_breast_cancer_tumors.html
mv xam MERIT2010_poster_LA.MS.html
mv xan VAPposter.html
mv xao meningitis_district_based_study.html
mv xap 101013_FINALDoH.html
mv xaq preterm_birth.html
mv xar development_of_executive_function.html
mv xas modelling_malaria.html
mv xat point_processes.html
mv xau modelling_spatio-temporal_variation.html
mv xav decline_in_renal_function.html
mv xaw diabetes_mellitus.html
mv xax NACFposter6Oct.html
mv xay AEGISS_project.html
mv xaz double_blind_catheter.html
mv xba impulsivity_vs_apathy.html
mv xbb ECF_Weight_29May.html
mv xbc parkinson.html
mv xbd HotspotMethods_PosterDraft.html
mv xbe Kirk_LILAC_Poster_7_October_v2.html
mv xbf malaria_changes.html
mv xbg lancet_seasonal_influenza.html
mv xbh MLW-MRC_Poster08Dec2014_MGC_PJD.html
mv xbi ISDS2015_poster_gi_early_detection.html
mv xbj ziyu_july_2016.html
mv xbk Fran_20180405-Symposium_Poster.html
